---
- name: "Add EPEL repository"
  yum:
    name: "{{epel_url}}"
    state: present
- name: "Install nginx"
  yum:
    name: "nginx"
    state: latest
- name: "Copy nginx.conf"
  template:
    src: app.conf
    dest: /etc/nginx/nginx.conf
- name: "Start nginx"
  service:
    name: "nginx"
    state: restarted